server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 11
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /hmdianping # 虚拟主机
    username: hmdianping # 用户名
    password: 123456 # 密码
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        acknowledge-mode: manual
        prefetch: 1

    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 控制台地址
        port: 8719 # 客户端端口


mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

hmdp:
  jwt:
#    # 设置jwt签名加密时使用的秘钥
#    admin-secret-key: itcast
#    # 设置jwt过期时间
#    admin-ttl: 7200000
#    # 设置前端传递过来的令牌名称
#    admin-token-name: token
    user-secret-key: ThisIsA32BytesLongSecretKeyForHS256
    user-ttl: 7200000
    user-token-name: authorization


canal:
  destination: example # canal的集群名字，要与安装canal时设置的名称一致
  server: 127.0.0.1:11111 # canal服务地址
